/** @type {import("tailwindcss").Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "accdoo-primary": "#0152A4",
        "secondary-blue": "#155DFC",
        "secondary-blue-dark": "#014FE0",
        "main-text": "#001D39",
        "nav-text": "#071F3A",
        "gray-800": "#4B4B52",
        success: "#13C276",
        danger: "#FB2C36",
        "search-placeholder": "#B2AFBC",
        "filter-surface": "#FAFAFA",
        "filter-border": "#C5C2D1",
        "filter-active": "#EBF5FF",
        "menu-border": "#E0DEE6",
        "menu-selected": "#EEF4FF",
        "search-surface": "#FEFEFE",
        "search-border": "#EFEFEF",
        "hero-accent": "#B4DCFF",
        "hero-white": "#FFFFF9",
        "match-surface": "#0F241F",
        "match-text": "#87DEB4",
        "theme-track": "#EDF3FB",
        "theme-border": "#D7DFEA",
        "avatar-surface": "#D8E8FF",
        "icon-muted": "#A8B0BE",
        "load-border": "#BFC7D4",
        page: "var(--page-bg)",
        nav: "var(--nav-bg)",
        surface: "var(--surface-bg)",
        card: "var(--card-bg)",
        "text-main": "var(--text-main)",
        "text-muted": "var(--text-muted)",
        "text-soft": "var(--text-soft)",
        "text-faint": "var(--text-faint)",
        "line-soft": "var(--line-soft)",
        "line-strong": "var(--line-strong)",
      },
      boxShadow: {
        search: "0 16px 42px rgba(15, 23, 42, 0.07)",
        "search-dark": "0 20px 48px rgba(0, 0, 0, 0.28)",
        card: "var(--shadow-card)",
        "card-hover": "0 0 40.5px rgba(0, 0, 0, 0.08)",
        "sort-bar": "0 10px 30px rgba(15, 23, 42, 0.055)",
        "sort-active": "1px 3px 15.1px rgba(0, 0, 0, 0.27)",
        "post-job-inset": "inset 0 4px 4px rgba(0, 0, 0, 0.11)",
        "control": "0 1px 2px rgba(15, 23, 42, 0.03)",
        "action": "1px 1px 6.6px rgba(0, 0, 0, 0.09)",
        "nav-line": "0 1px 0 rgba(2, 18, 38, 0.055)",
      },
      borderRadius: {
        sort: "9px",
      },
      borderWidth: {
        hairline: "0.5px",
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-140%) skewX(-20deg)" },
          "100%": { transform: "translateX(280%) skewX(-20deg)" },
        },
        "border-spin": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
      animation: {
        shimmer: "shimmer 2.8s ease-in-out infinite",
        "border-spin": "border-spin 2.2s linear infinite",
      },
    },
  },
};
