export const jobFilters = ["Remote/Onsite", "Salary Range", "Experience", "Tech Stack"];

export const jobs = [
  {
    id: 1,
    title: "Senior Frontend Engineer",
    company: "TechNova Lanka",
    location: "Colombo",
    mode: "Hybrid",
    type: "Full-time",
    salary: "LKR 180k - 320k",
    tags: ["React", "Next.js"],
    match: "92%",
    status: "Strong Match",
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "GlobalSys Partners",
    location: "Kandy",
    mode: "Remote",
    type: "Contract",
    salary: "LKR 120k - 220k",
    tags: ["React", "TypeScript"],
    match: "68%",
    status: "Potential Match",
  },
  {
    id: 3,
    title: "Data Analyst",
    company: "QuantCorp LK",
    location: "Galle",
    mode: "Onsite",
    type: "Full-time",
    salary: "LKR 100k - 180k",
    tags: ["Python", "Power BI"],
    match: "72%",
    status: "Good Match",
  },
  {
    id: 4,
    title: "Backend Developer",
    company: "CloudNest Labs",
    location: "Jaffna",
    mode: "Hybrid",
    type: "Full-time",
    salary: "LKR 160k - 280k",
    tags: ["FastAPI", "PostgreSQL"],
    match: "88%",
    status: "Strong Match",
  },
];