export const jobFilters = [
  "Remote/Onsite",
  "Salary Range",
  "Experience",
  "Tech Stack",
];

export const jobs = [
  {
    id: 1,
    title: "Senior Frontend Engineer",
    company: "TechNova Lanka",
    logoText: "TN",
    verified: true,
    category: "Information & Communication Technology",
    location: "Colombo, Sri Lanka",
    mode: "Hybrid",
    type: "Full-Time",
    salary: "LKR 180,000 - 320,000/month",
    tags: ["React", "Next.js", "Tailwind CSS"],
    match: "92%",
    status: "Strong match based on your frontend skills",
    postedDate: "27/05/26",
    aiRecommended: true,
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "GlobalSys Partners",
    logoText: "GS",
    verified: true,
    category: "Software Engineering > Frontend Development",
    location: "Kandy, Sri Lanka",
    mode: "Remote",
    type: "Contract",
    salary: "LKR 120,000 - 220,000/month",
    tags: ["React", "JavaScript", "UI Development"],
    match: "68%",
    status: "Potential match with room to improve",
    postedDate: "27/05/26",
    aiRecommended: false,
  },
  {
    id: 3,
    title: "Data Analyst",
    company: "QuantCorp LK",
    logoText: "QC",
    verified: true,
    category: "Data & Analytics > Business Intelligence",
    location: "Galle, Sri Lanka",
    mode: "Onsite",
    type: "Full-Time",
    salary: "LKR 100,000 - 180,000/month",
    tags: ["Python", "Power BI", "SQL"],
    match: "72%",
    status: "Good match for analytical skill set",
    postedDate: "27/05/26",
    aiRecommended: false,
  },
  {
    id: 4,
    title: "Backend Developer",
    company: "CloudNest Labs",
    logoText: "CN",
    verified: true,
    category: "Software Engineering > Backend Development",
    location: "Jaffna, Sri Lanka",
    mode: "Hybrid",
    type: "Full-Time",
    salary: "LKR 160,000 - 280,000/month",
    tags: ["FastAPI", "PostgreSQL", "REST API"],
    match: "88%",
    status: "Strong match based on backend API experience",
    postedDate: "27/05/26",
    aiRecommended: true,
  },
];